apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.database.name }}-storage"
spec:
  accessModes: {{ .Values.database.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.database.storage.size }}
