apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.database.container.port }}
      targetPort: {{ .Values.database.container.port }}
  selector:
    app: {{ .Values.database.name }}
