apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webapp.name}}
  labels:
    app: {{ .Values.webapp.name }}
    group: {{ .Values.webapp.group }}
spec:
  replicas: {{ .Values.webapp.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.webapp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.webapp.name }}
        group: {{ .Values.webapp.group }}
    spec:
      containers:
        - name: {{ .Values.webapp.name }}
          image: "{{ .Values.webapp.container.image.name}}:{{ .Values.webapp.container.image.tag }}"
          imagePullPolicy: {{ .Values.webapp.container.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.webapp.container.port }}
              protocol: TCP
