webapp:
  replicaCount: 1
  name: webapp
  group: webapp
  containers:
    image:
      name: ghcr.io/remarket-se2/webapp
      pullPolicy: IfNotPresent
      tag: latest
    port: 3000
    env:
      google_client_id: ""
      google_client_secret: ""
      jwt_secret: ""
      secret: ""
      nextauth_secret: ""
  service:
    type: ClusterIP
    port: 80
  config:
    name: webapp-config
    data:
  ingress:
    className: nginx
    host: webapp.local



database:
  replicaCount: 1
  name: database
  container:
    image:
      pullPolicy: IfNotPresent
      name: postgres
      tag: latest
    port: 5432
    env:
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "mydatabase"
  storage:
    size: 5Gi
    accessModes: ["ReadWriteOnce"]

controller:
  service:
    loadBalancerIP: ""
