webapp:
  replicaCount: 2
  name: webapp
  group: webapp
  container:
    image:
      name: remarket/webapp
      pullPolicy: IfNotPresent
      tag: latest
    port: 3000
  service:
    type: LoadBalancer
    port: 80
  config:
    name: webapp-config
    data:
  ingress:
    className: nginx
    host: webapp.local


database:
  replicaCount: 1
  name: database
  container:
    image:
      pullPolicy: IfNotPresent
      name: postgres
      tag: latest
    port: 5432
    env:
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "mydatabase"
  storage:
    size: 5Gi
    accessModes: ["ReadWriteOnce"]
