webapp:
  replicaCount: 1
  name: webapp
  group: webapp
  containers:
    image:
      name: ghcr.io/remarket-se2/webapp
      pullPolicy: Always
      tag: latest
    port: 3000
    env:
      google_client_id: ""
      google_client_secret: ""
      jwt_secret: "secret"
      secret: "secret"
      nextauth_secret: "secret"
      next_public_app_url: "http://localhost:3000"
      nextauth_url: "http://localhost:3000"
      stripe_secret_key: "secret"
      stripe_webhook_secret: "secret"
  service:
    type: ClusterIP
    port: 80
  config:
    name: webapp-config
    data:
  ingress:
    className: nginx
    host: remarket-se2.xyz

database:
  replicaCount: 1
  name: database
  container:
    image:
      pullPolicy: IfNotPresent
      name: postgres
      tag: latest
    port: 5432
    env:
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "mydatabase"
  storage:
    size: 5Gi
    accessModes: ["ReadWriteOnce"]

ingress-nginx:
  controller:
    service:
      type: LoadBalancer
      loadBalancerIP: "34.118.105.194"
    progressDeadlineSeconds: 30

issuer:
  enabled: false

kube-prometheus-stack:
  nodeExporter:
    enabled: false
  grafana:
    defaultDashboardsEnabled: true
  prometheus:
    prometheusSpec:
      maximumStartupDurationSeconds: 60
