name: Provisioning

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  build-webapp:
    name: Build webapp
    uses: ./.github/workflows/build.yaml
    with:
      repository: ReMarket-SE2/webapp
      branch: master
      dockerfile-path: docker
      image-name: webapp
      image-tag: '1.0'
    secrets: inherit
