name: Provisioning

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Select the mode of operation'
        required: true
        default: 'Destroy'
        type: choice
        options:
          - Create
          - Destroy
  push:
jobs:
  terraform:
    name: 'Provisioning cluster'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: |
        cd infrastructure
        terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        TF_VAR_project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
        TF_VAR_region: ${{ secrets.GOOGLE_REGION }}
        TF_VAR_zone: ${{ secrets.GOOGLE_ZONE }}

    - name: Terraform Plan
      run: |
        cd infrastructure
        terraform plan
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        TF_VAR_project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
        TF_VAR_region: ${{ secrets.GOOGLE_REGION }}
        TF_VAR_zone: ${{ secrets.GOOGLE_ZONE }}

    - name: Terraform Apply
      if: github.event.inputs.mode == 'Create'
      run: |
        cd infrastructure
        terraform apply -auto-approve -lock=false
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        TF_VAR_project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
        TF_VAR_region: ${{ secrets.GOOGLE_REGION }}
        TF_VAR_zone: ${{ secrets.GOOGLE_ZONE }}

    - name: Terraform Destroy
      if: github.event.inputs.mode != 'Create'
      run: |
        cd infrastructure
        terraform destroy -auto-approve -lock=false
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        TF_VAR_project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
        TF_VAR_region: ${{ secrets.GOOGLE_REGION }}
        TF_VAR_zone: ${{ secrets.GOOGLE_ZONE }}
